### PR TITLE
Use baseUrl instead of ip

### PR DESCRIPTION
**Pull request by stokito**
To connect to the switch currently we use only IP and always `http://` schema. But a switch may have a https schema, hostname and port. This is useful if you are trying to expose the switch for the external access over internet (which is not a good idea but sometimes really needed).
The PR is reworked #11 and is based on #17 so first commits are not really related to the feature.

### CODE REVIEW

**Comment by stokito** [comment]
@Japh could you please check the PR?

**Comment by Japh** [comment]
@stokito Looks good! I'm not sure about the changes to `switches.json` though. Seems local access should be default, rather than including the DynDNS variation?

**Comment by stokito** [comment]
This is an example, so the first switch remains local but the second I made as an example of using DuckDNS.org

**Review by organismzero — APPROVED** [review]
Looks good, thank you!

**Comment by Japh** [comment]
Oh yeah, I didn't notice that sorry. Will merge, thank you!

**Pull request merged**
